# Site settings
title: Research & Develop Open Ventures (RDOV)
description: # this means to ignore newlines until "baseurl:"
  RDOV is licensed under
  <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>.<br/>
  © 2015 Deginner.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rdov.co/" # the base hostname & protocol for your site
repo_edit: "https://bitbucket.org/deginner/rdov/src/master/"
toc_title: Contents

highlighter: null
permalink: /:title

# Build settings
markdown: kramdown
exclude: ['build_scripts', 'contributors.txt']
