# Site settings
title: Research & Develop Open Ventures (RDOV)
description: # this means to ignore newlines until "baseurl:"
  RDOV is licensed under
  <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>.<br/>
  © 2015 Deginner.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rdov.github.io/" # the base hostname & protocol for your site
repo_edit: "https://github.com/rdov/rdov.github.io/edit/master/"
toc_title: Contents

highlighter: 'pygments'
permalink: /:title

# Build settings
markdown: kramdown
gems: ['kramdown']
exclude: ['build_scripts', 'contributors.txt', 'img_src', 'config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
